# Generated by Django 4.2.14 on 2024-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('beer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('plato', models.CharField(max_length=10)),
                ('alcohol', models.CharField(max_length=10)),
                ('price_051', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_041', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_031', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_021', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
