# Generated by Django 4.2.14 on 2024-08-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponuka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beertablerow',
            name='number',
        ),
    ]
