# Generated by Django 4.2.14 on 2024-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponuka', '0002_remove_beertablerow_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beertablerow',
            name='price_021',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beertablerow',
            name='price_031',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beertablerow',
            name='price_041',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beertablerow',
            name='price_051',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
