# Generated by Django 4.2.14 on 2024-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponuka', '0003_alter_beertablerow_price_021_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozadolVYCAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povod', models.CharField(max_length=100)),
                ('nazov', models.CharField(max_length=100)),
                ('styl', models.CharField(max_length=100)),
                ('plato', models.CharField(max_length=10)),
                ('alkohol', models.CharField(max_length=10)),
                ('price_05l', models.CharField(default='/', max_length=5)),
                ('price_04l', models.CharField(default='/', max_length=5)),
                ('price_03l', models.CharField(default='/', max_length=5)),
                ('price_02l', models.CharField(default='/', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='VydricaVYCAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povod', models.CharField(max_length=100)),
                ('nazov', models.CharField(max_length=100)),
                ('styl', models.CharField(max_length=100)),
                ('plato', models.CharField(max_length=10)),
                ('alkohol', models.CharField(max_length=10)),
                ('price_05l', models.CharField(default='/', max_length=5)),
                ('price_04l', models.CharField(default='/', max_length=5)),
                ('price_03l', models.CharField(default='/', max_length=5)),
                ('price_02l', models.CharField(default='/', max_length=5)),
            ],
        ),
    ]
