# Generated by Django 4.2.14 on 2024-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ffname', models.CharField(max_length=100)),
                ('Femail', models.EmailField(max_length=254)),
                ('Fdate', models.DateField()),
                ('Fpoznamka', models.TextField(blank=True)),
                ('Foption', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pouzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
            ],
        ),
    ]
